"""initial schema

Revision ID: 7d2686ad5b0c
Revises: 
Create Date: 2026-09-01 23:12:30.958473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2686ad5b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('off_topic_strikes', sa.Integer(), nullable=False),
    sa.Column('terminated', sa.Boolean(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('requested_callback_time', sa.String(length=120), nullable=True),
    sa.Column('last_message_sid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='uq_conversation_sessions_phone')
    )
    op.create_index('ix_conversation_sessions_expires_at', 'conversation_sessions', ['expires_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('business_summary', sa.String(length=500), nullable=True),
    sa.Column('termination_reason', sa.String(length=32), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('off_topic_strikes', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('requested_callback_time', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_phone', 'leads', ['phone'], unique=False)
    op.create_table('processed_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_sid', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('response_body', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid', name='uq_processed_messages_sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_messages')
    op.drop_index('ix_leads_phone', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_conversation_sessions_expires_at', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
